# -*- coding: utf-8 -*-
# @Time    : 2019/1/31 9:56
# @Author  : chengz
# @File    : 新增客户.py
# @Software: PyCharm
from selenium import webdriver
import time

driver = webdriver.Chrome()
driver.get("http://t.oa.quanhoo.com")
driver.maximize_window()
driver.find_element_by_name("logincode").send_keys("admin")
driver.find_element_by_name("pwd").send_keys("123456")
driver.find_element_by_css_selector("[class='el-button el-button--primary']").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='数据看板']").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='CRM']").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='客户管理']").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='新增客户']").click()
time.sleep(2)
driver.find_element_by_xpath("//label[text()='手机号']/following-sibling::div//div/input").send_keys("13712121265")
time.sleep(2)
driver.find_element_by_xpath("//button/span[text()='下一步']").click()
time.sleep(2)
driver.find_element_by_xpath("//label[text()='真实姓名']/following-sibling::div//div/input").send_keys(u"测试")
time.sleep(2)
driver.find_element_by_xpath("//div[@class='el-form-item__content']/label[@role='radio'][2]/span[2]").click()
time.sleep(2)
driver.find_element_by_xpath("//label[text()='客户类型']/following-sibling::div//div/div/input").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='个人代理']").click()
time.sleep(2)
driver.find_element_by_xpath("//label[text()='推荐人']/following-sibling::div//div/div/input").send_keys(u"测试")
time.sleep(2)
driver.find_element_by_xpath("//span[text()='测试5（19925328096）']").click()
time.sleep(2)
driver.find_element_by_xpath("//button/span[text()='下一步']").click()
time.sleep(2)
driver.find_element_by_xpath("//label[text()='项目']/following-sibling::div//div/div/input").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='护肤彩妆']").click()
time.sleep(2)
# 点击加入时间
driver.find_element_by_xpath("//label[text()='加入时间']/following-sibling::div//div/input").click()
time.sleep(2)
# 选择第一个
driver.find_element_by_xpath("//table[@class='el-date-table']/tbody/tr[2]/td[1]//span").click()
# driver.execute_script("document.getElementsByClassName('el-input__inner')[1].value='2019-01-31'")
time.sleep(2)
driver.find_element_by_xpath("//label[text()='代理级别']/following-sibling::div//div/div/input").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='二级']").click()
time.sleep(2)
driver.find_element_by_xpath("//div[@class='el-form-item__content']/label[@role='radio'][2]/span[2]").click()
time.sleep(2)
driver.find_element_by_xpath("//label[text()='班长']/following-sibling::div//div/div/input").send_keys(u"曾1")
time.sleep(2)
driver.find_element_by_xpath("//span[text()='曾1（11）']").click()
time.sleep(2)
driver.find_element_by_xpath("//span[text()='保存']").click()
time.sleep(2)
# driver.quit()
